<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-N48P201" failures="1" tests="7" name="Nopackage" time="27.405" errors="0" timestamp="2025-05-11T05:13:36 IST">
  <testcase classname="test.TC_01" name="login" time="0.32"/>
  <testcase classname="test.TC_01" name="login" time="0.268">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]
at test.TC_01.login(TC_01.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="test.TC_01" name="login" time="0.299"/>
  <testcase classname="test.TC_01" name="login" time="5.309"/>
  <testcase classname="test.TC_01" name="login" time="0.336"/>
  <testcase classname="test.TC_01" name="login" time="0.323"/>
  <testcase classname="test.TC_02" name="login" time="6.51"/>
  <testcase classname="base.base" name="@AfterSuite tearDownReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownReport -->
  <testcase classname="base.base" name="@BeforeSuite setupReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupReport -->
</testsuite> <!-- Nopackage -->
